### PR TITLE
Fixed HTML validation errors.

### PR DESCRIPTION
**Pull request by Psiale**
The changes on this pull request are: 
* Fixed the h1 elements to be h2 as the HTML validator suggested.

### CODE REVIEW

**Review by imhta — COMMENTED** [review]
# PR Invalid 
### Hello 👋 @Psiale,  Marking code review request as invalid, because this PR doesn't have a descriptive title and a description.

---
#### Don't forgot to request for another code review
---
**Pon Muthu Selvam**
_If you have any queries, feel free to ping me on slack_

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Medium size of website is not very responsive. Some styling errors need to be corrected.

**Comment by pelzolga123** [comment]
## Hi Alexis!  
### Your project looks :+1: amazing!
But there are some changes needed:

* [ ] Small and medium versions need to be more responsive, right now they have white line on rightmost part. You can see very clear, it stars with havbar having white space after hamburger icon:
image
image

* [ ] Large version of `Latest news section` should contain 4 articles per row. [Link to website](https://thenextweb.com/) . Right now you have divs there.

* [ ] Medium version of `Latest news section` should contain 3 articles per row. [Link to website](https://thenextweb.com/) . Right now you have:
image

Original:
image

* [ ] Large version of `Latest funding section` should contain 4 articles per row. [Link to website](https://thenextweb.com/). Right now you have divs there.

* [ ] Medium version of `Latest funding section` should contain 3 articles per row. [Link to website](https://thenextweb.com/).  Right now you have:
image

Original:
image

* [ ] Medium version of `Categories (Apps, GERA, Tech, etc) section` should contain 2 category boxes per row. [Link to website](https://thenextweb.com/).  Right now you have:
image

Original:
 image

* [ ] Medium version of `Latest deals` should contain 2 category boxes per row. [Link to website](https://thenextweb.com/). Right now you have:
image

Original:
 image

* [ ] Footer is not aligned properly:
image

Original:
 image

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by shshamim63** [comment]
## Status :recycle: !! Required Changes !!
__
Hi @Psiale  :wave: .
Good job :clap: . You are trying hard to make the changes, but still there are some issues that you need to fix. And i am sure that you will fill the gaps. :sunglasses: 
___
#### Please follow the instructions below to complete this project. :smile: 
___
## :spades: [Mandatory Changes] :spades: 
___
##### :space_invader: [Medium Screen]
You have defined your medium screen that contain 768-1022 px. So at that specified the rendering should be same. But in your project they are not.
1. **Latest news section** -> It aligns 3 articles per row. The left one should render on the next line but at the left most side.
###### Actual one ->
image
###### Your one(768px) ->
image
###### Your one(1021px) ->
image
2. **Latest funding section** -> It aligns 3 articles per row
###### Actual one ->
image
###### Your one(768px) ->
image
###### Your one(1021px) ->
image
___
##### You have covered the other latest deals properly. So I am sure that you know how to do it. Please fix the above mentioned issue and send review request.
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
White line should be removed from rightmost side of the project.

**Comment by pelzolga123** [comment]
## Good job, implementing most of the required changes :+1: 
But still that white line on rightmost side of the page should be removed from small and medium versions before project can be approved:
image

image

[OPTIONAl] You can also center all content in small and medium versions and project will look better. 

### Please kindly fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Your project is one of the best I've seen! @Psiale and @imhta  :smile:
I commend you both, this is really awesome. It feels like the real thing!. Your project is very responsive however there is one more tiny detail to correct as regards the responiveness and your readme file needs some fleshing out as well.

# Summary
* Please add a more descriptive readme to the project, use this as [an example](https://github.com/Oluwadamilareolusakin/weather-lord/blob/master/README.md)
screenshot
* Please go through each section on the page and ensure the left and right padding(space on the left and right on the page) is the same for each. Currently some sections are too much to one side, it creates a little bit of inconsistency and steals shine from your project.

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi Alexis👏,
You have really cloned the project🙂. Here one thing you have to do to put the icing on the cake.
- [ ] Html validator is raising three warnings, kindly address them.[here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png)
## That is it, make this change and submit the project for review🙂.
#### Happy coding🙂🙂🙂
Addo Forison

**Review by imhta — APPROVED** [review]
# Project approved 🎉 

### Hello  @Psiale  , 👋 You have done a great job in this project 👏 




----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

**Pull request merged**
